{% set name = "aim-ui" %}
{% set version = "3.20.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aim-ui-{{ version }}.tar.gz
  sha256: 4e8c7dfe9a2b5031390c07309c47d1175e045c777fbf54c7c235dacd73988df3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - aim_ui
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/aim-ui/
  summary: Aim UI
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
    - gorarakelyan
    - synapticarbors
